//
//  HomeRouter.swift
//  PokeDex
//
//  Created by Pedro Ramos on 22/10/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
    func routeToDetailPokemon(id: Int, name: String)
}

protocol HomeDataPassing {
    var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
    weak var viewController: HomeViewController?
    var dataStore: HomeDataStore?
    
    func routeToDetailPokemon(id: Int, name: String) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        guard let detailPokemonViewController = storyboard.instantiateViewController(withIdentifier: DetailPokemonViewController.identifier) as? DetailPokemonViewController else { return }
        detailPokemonViewController.id = id
        detailPokemonViewController.name = name
        viewController?.navigationController?.pushViewController(detailPokemonViewController, animated: true)
    }
}
