//
//  DetailPokemonViewController.swift
//  PokeDex
//
//  Created by Pedro Ramos on 23/10/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPokemonDisplayLogic: class {
    func displayImage(viewModel: DetailPokemonScene.LoadImage.ViewModel)
    func displayInitialData(viewModel: DetailPokemonScene.Load.ViewModel)
    func displayMessageError(error: Error)
}

class DetailPokemonViewController: UIViewController {
    var id: Int = -1
    var name: String = String()
    var interactor: DetailPokemonBusinessLogic?
    var router: (NSObjectProtocol & DetailPokemonRoutingLogic & DetailPokemonDataPassing)?
    var model: PokemonResponse?
    
    typealias dataCell = (UIImage?, String, String)
    var data: [dataCell] = []
    
    @IBOutlet private weak var imageView: UIImageView!
    @IBOutlet private weak var typeImageView: UIImageView!
    @IBOutlet private weak var tableView: UITableView!
    
    // MARK: Object lifecycle
    
    private func setup() {
        let viewController = self
        let interactor = DetailPokemonInteractor()
        let presenter = DetailPokemonPresenter()
        let router = DetailPokemonRouter()
        let worker = DetailPokemonWorker()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.worker = worker
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        title = name.uppercased()
        tableView.layer.cornerRadius = 6.0
        tableView.delegate = self
        tableView.dataSource = self
        setup()
        loadInitialData()
    }
    
    func loadInitialData() {
        interactor?.doLoadInitialData(request: DetailPokemonScene.Load.Request(id: self.id))
        interactor?.doLoadImageData(request: DetailPokemonScene.LoadImage.Request(id: self.id))
    }
}

extension DetailPokemonViewController: DetailPokemonDisplayLogic {
    func displayInitialData(viewModel: DetailPokemonScene.Load.ViewModel) {
        self.model = viewModel.pokemon
        data.append( (nil, "ID:", viewModel.pokemon.id.numberWithZeros(number: 10)) )
        data.append( (nil, "Base Experience:", "\(viewModel.pokemon.baseExperience) EXP" ) )
        data.append( (nil, "height:", "\(viewModel.pokemon.height) Decimetres") )
        data.append( (nil, "weight:", "\(viewModel.pokemon.weight) Hectograms") )
        for item in viewModel.pokemon.types {
            data.append( (item.pokemonType.typeImage, "TYPE:", item.pokemonType.description) )
        }
        DispatchQueue.main.async {
            self.view.backgroundColor = viewModel.pokemon.types.first?.pokemonType.color
            self.typeImageView.image = viewModel.pokemon.types.first?.pokemonType.tagImage
            self.tableView.reloadData()
        }
    }
    
    func displayImage(viewModel: DetailPokemonScene.LoadImage.ViewModel) {
        DispatchQueue.main.async {
            self.imageView.image = viewModel.image
        }
    }
    
    func displayMessageError(error: Error) {
        
    }
}

extension DetailPokemonViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return self.data.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let item = data[indexPath.row]
        return customCell(item: item)
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 60
    }
    
    func customCell(item: dataCell) -> UITableViewCell{
        let cell = UITableViewCell(style: .subtitle, reuseIdentifier: "cell")
        cell.imageView?.image = item.0
        cell.textLabel?.font = UIFont.boldSystemFont(ofSize: 20)
        cell.textLabel?.text = item.1.uppercased()
        cell.detailTextLabel?.font = UIFont.systemFont(ofSize: 16)
        cell.detailTextLabel?.text = item.2
        return cell
    }
}

extension DetailPokemonViewController {
    static var identifier: String {
        return "DetailPokemonViewController"
    }
}
