//
//  DetailPokemonRouter.swift
//  PokeDex
//
//  Created by Pedro Ramos on 23/10/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailPokemonRoutingLogic {
}

protocol DetailPokemonDataPassing {
    var dataStore: DetailPokemonDataStore? { get }
}

class DetailPokemonRouter: NSObject, DetailPokemonRoutingLogic, DetailPokemonDataPassing {
    weak var viewController: DetailPokemonViewController?
    var dataStore: DetailPokemonDataStore?
}
