//
//  DetailPokemonModels.swift
//  PokeDex
//
//  Created by Pedro Ramos on 23/10/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DetailPokemonScene {
    // MARK: Use cases
    
    enum Load {
        struct Request {
            var id: Int
        }
        struct Response {
            var pokemon: PokemonResponse
        }
        struct ViewModel {
            var pokemon: PokemonResponse
        }
    }
    
    enum LoadImage {
        struct Request {
            var id: Int
        }
        struct Response {
            var image: UIImage?
        }
        struct ViewModel {
            var image: UIImage?
        }
    }
}
