//
//  ItemsPresenterTests.swift
//  PokeDex
//
//  Created by Pedro Ramos on 11/11/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import PokeDex
import XCTest

class ItemsPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ItemsPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupItemsPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupItemsPresenter() {
        sut = ItemsPresenter()
    }
    
    // MARK: Test doubles
    
    class ItemsDisplayLogicSpy: ItemsDisplayLogic {
        var displaySomethingCalled = false
        
        func displaySomething(viewModel: Items.Something.ViewModel) {
            displaySomethingCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentSomething() {
        // Given
        let spy = ItemsDisplayLogicSpy()
        sut.viewController = spy
        let response = Items.Something.Response()
        
        // When
        sut.presentSomething(response: response)
        
        // Then
        XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
