//
//  ItemsInteractorTests.swift
//  PokeDex
//
//  Created by Pedro Ramos on 11/11/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import PokeDex
import XCTest

class ItemsInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: ItemsInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupItemsInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupItemsInteractor() {
        sut = ItemsInteractor()
    }
    
    // MARK: Test doubles
    
    class ItemsPresentationLogicSpy: ItemsPresentationLogic {
        var presentSomethingCalled = false
        
        func presentSomething(response: Items.Something.Response) {
            presentSomethingCalled = true
        }
    }
    
    // MARK: Tests
    
    func testDoSomething() {
        // Given
        let spy = ItemsPresentationLogicSpy()
        sut.presenter = spy
        let request = Items.Something.Request()
        
        // When
        sut.doSomething(request: request)
        
        // Then
        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
