//
//  PokemonsInteractor.swift
//  PokeDex
//
//  Created by Pedro Ramos on 11/11/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemonsBusinessLogic {
    func doSomething(request: Pokemons.Something.Request)
}

protocol PokemonsDataStore {
    //var name: String { get set }
}

class PokemonsInteractor: PokemonsBusinessLogic, PokemonsDataStore {
    var presenter: PokemonsPresentationLogic?
    var worker: PokemonsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Pokemons.Something.Request) {
        worker = PokemonsWorker()
        worker?.doSomeWork()
        
        let response = Pokemons.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
