//
//  PokemonsPresenter.swift
//  PokeDex
//
//  Created by Pedro Ramos on 11/11/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PokemonsPresentationLogic {
    func presentSomething(response: Pokemons.Something.Response)
}

class PokemonsPresenter: PokemonsPresentationLogic {
    weak var viewController: PokemonsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Pokemons.Something.Response) {
        let viewModel = Pokemons.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
