//
//  MovesInteractor.swift
//  PokeDex
//
//  Created by Pedro Ramos on 11/11/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovesBusinessLogic {
    func doSomething(request: Moves.Something.Request)
}

protocol MovesDataStore {
    //var name: String { get set }
}

class MovesInteractor: MovesBusinessLogic, MovesDataStore {
    var presenter: MovesPresentationLogic?
    var worker: MovesWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Moves.Something.Request) {
        worker = MovesWorker()
        worker?.doSomeWork()
        
        let response = Moves.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
