//
//  DetailPokemonPresenter.swift
//  PokeDex
//
//  Created by Pedro Ramos on 23/10/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailPokemonPresentationLogic {
    func presentPokemon(response: DetailPokemonScene.Load.Response)
    func presentImage(response: DetailPokemonScene.LoadImage.Response)
    func presentMessageError(error: Error)
}

class DetailPokemonPresenter: DetailPokemonPresentationLogic {
    weak var viewController: DetailPokemonDisplayLogic?
    
    func presentPokemon(response: DetailPokemonScene.Load.Response) {
        viewController?.displayInitialData(viewModel: DetailPokemonScene.Load.ViewModel(pokemon: response.pokemon))
    }
    
    func presentImage(response: DetailPokemonScene.LoadImage.Response) {
        viewController?.displayImage(viewModel: DetailPokemonScene.LoadImage.ViewModel(image: response.image))
    }
    
    func presentMessageError(error: Error) {
        viewController?.displayMessageError(error: error)
    }
}
