//
//  HomePresenter.swift
//  PokeDex
//
//  Created by Pedro Ramos on 22/10/19.
//  Copyright (c) 2019 Pedro Ramos. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentAllPokemons(response: HomeScene.Load.Response)
    func presentMessageError(error: Error)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?
    
    func presentAllPokemons(response: HomeScene.Load.Response) {
        let viewModel = HomeScene.Load.ViewModel(pokemons: response.pokemons)
        viewController?.displayInitialData(viewModel: viewModel)
    }
    
    func presentMessageError(error: Error) {
        viewController?.displayMessageError(error: error)
    }
}
